server:
  port: 30000
spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tQyTaMM1PD7zkfaxF4r
      secret-key: EvyzMOMPYhq67EwZAJM7rOwZGXwvNy
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: my-mall-study
